### ISSUE TITLE
lockdown node version with an .nvmrc file?

### ISSUE THREAD

**Issue by cameronwp** [xOPERATIONS/maestro#82]
Any thoughts on adding a `.nvmrc` file to specify a node version for use with building `maestro`? If you haven't seen an `.nvmrc` file before, it's from a script called [nvm](https://github.com/nvm-sh/nvm), which makes it easy to manage installed node versions.

Either way, I feel strongly that it's a good idea to explicitly specify the version of node that `maestro` supports.

Pros:
* drastically reduce the odds of bugs due to mismatched node versions between maintainers
* make it explicit exactly which version of node the project depends on

Cons:
* adds a file to the repo?
* maybe there's another preferred way of managing node versions that you all would like to use?

FWIW, I'm using node version 8 because that's what happened to be installed on my system. The latest node LTS version is v12.

**Comment by jamesmontalvo3** [comment]
Fine by me. Add it. Travis tests against 10 and 12.

**Comment by cameronwp** [comment]
Found another con while testing. `npm link` symlinks an executable index.js file into your `$PATH`, which is what allows you to run `maestro` from elsewhere on your filesystem. If you use nvm, then you *must* ensure that you're using the same version of node while in a procedure repo in order for `maestro` to be found in their `$PATH`. In practice, this means that users are more likely to get errors when running `maestro` if they aren't knowledgeable about how node versions are being managed on their system.

Installing node globally without a version manager generally doesn't come with the same issues.

Two ways to avoid this:
1. Do nothing. Let users manage their Node installations however they want, but maybe _suggest_ a version of Node in the README.
2. Require that devs use a specific version of Node. Recommend using a tool like nvm. Then change the installation process to ensure that Node versions don't matter for end users. This likely means creating an executable that end users (not devs) can download and run in lieu of recommending that folks clone the repo and `npm link` to install.

I'd recommend option 1 for now and maybe revisit 2 if/when you want to address end user installation later.

**Comment by cameronwp** [comment]
Closing for now.
